name: pipecat_client_flutter
description: Flutter client SDK for Pipecat AI with clean architecture and provider state management
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Essential only - following pipecat-client-web approach exactly
  web_socket_channel: ^2.4.0    # WebSocket transport
  
  # Audio recording and playback (mobile support)
  record: ^5.0.4                 # Microphone recording to PCM stream
  flutter_sound: ^9.2.13        # PCM stream playback
  permission_handler: ^11.0.1    # Audio permissions
  
  # State management
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true